#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Apache-Wyrd
version:      0.90
version_from: Wyrd.pm
installdirs:  site
requires:
    Crypt::Blowfish:               
    Apache::Constants:             
    MIME::Base64:                  
    HTML::Entities:                
    Apache::URI:                   
    Apache::Util:                  
    LWP::UserAgent:                
    Apache:                        1.26
    Apache::Request:               
    DBI:                           
    Digest::MD5:                   
    XML::Dumper:                   0.67
    HTTP::Request::Common:         
    BerkeleyDB:                    0.23
    Class::Singleton:              
    Apache::Cookie:                

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.12
