#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Apache-Wyrd
version:      0.84
version_from: Wyrd.pm
installdirs:  site
requires:
    Class::Singleton:              
    Apache::Test:                  1.08
    Apache::Cookie:                
    DBI:                           
    Apache::Util:                  
    BerkeleyDB:                    0.23
    HTML::Entities:                
    XML::Dumper:                   0.67
    HTTP::Request::Common:         
    Apache::Constants:             
    Apache:                        1.26
    Digest::MD5:                   
    LWP::UserAgent:                
    Apache::URI:                   
    MIME::Base64:                  
    Apache::Request:               
    Crypt::Blowfish:               

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.12
