#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Apache-Wyrd
version:      0.87
version_from: Wyrd.pm
installdirs:  site
requires:
    HTTP::Request::Common:         
    HTML::Entities:                
    XML::Dumper:                   0.67
    MIME::Base64:                  
    Apache::Util:                  
    Apache::URI:                   
    DBI:                           
    BerkeleyDB:                    0.23
    Apache:                        1.26
    Class::Singleton:              
    Apache::Constants:             
    Crypt::Blowfish:               
    Apache::Cookie:                
    LWP::UserAgent:                
    Digest::MD5:                   
    Apache::Request:               

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.12
